### ISSUE TITLE
好像近排deepl对这个扩展进行了限制？！

### ISSUE THREAD

**Issue by mrkwong2022** [blueagler/DeepL-Crack#10]
使用扩展进行文本翻译几次后，即会收到以下提醒：

由于DeepL翻译器的访问量过大，目前服务受限。请稍后再试。 (429-1042901-T)

扩展为最新version。

**Comment by blueagler** [comment]
![Uploading Screenshot 2022-11-25 at 7.14.44 PM.png…]()
