### ISSUE TITLE
该会话已过期。请再次登录或稍后再试。 (401--32003-T)

### ISSUE THREAD

**Issue by shi131** [blueagler/DeepL-Crack#14]
This message appears after loading the latest version, and cannot be translated.
该会话已过期。请再次登录或稍后再试。 (401--32003-T)

**Comment by blueagler** [comment]
没有劫持到XMLHttpRequest, 你使用什么浏览器或者有魔改过吗

**Comment by rickychaw** [comment]
![image](https://user-images.githubusercontent.com/18382173/210191173-64fc731a-f0da-4eff-b8ea-bfc2b144ad13.png)

同样现象，而且还一直提示更新插件，但是已经是最新的release

**Comment by blueagler** [comment]
判断最新版的逻辑问题,下个版本修复
