### ISSUE TITLE
1.0.7版本提示错误信息

### ISSUE THREAD

**Issue by msjsc001** [blueagler/DeepL-Crack#16]
![image](https://user-images.githubusercontent.com/93178788/209550154-a5a3871a-11c7-4275-b14d-5a967d62554f.png)

[v1.0.7](https://github.com/blueagler/DeepL-Crack/releases/tag/v1.0.7) 版本在翻译输入框内贴入需要翻译的内容后提示上图错误信息

**Comment by msjsc001** [comment]
使用的时谷歌浏览器，COOKIS全部清理后还是这样。

**Comment by woshiyasuo** [comment]
Same problem

**Comment by blueagler** [comment]
截图控制栏报错

**Comment by msjsc001** [comment]
清理Cookie后可正常使用。
