### ISSUE TITLE
[Feature Request]Website translations.

### ISSUE THREAD

**Issue by toprak** [blueagler/DeepL-Crack#18]
Firstly I want to thank to you for creating this project, as a student which has a tight economy you literally saved me! (I can't buy it even though I have money it is not available on my country). So DeepL Chrome extension has a feature that called website translation for pro users, so can you make it work for us too please.

**Comment by toprak** [comment]
Anyways I've found a way:
convert it to pdf and translate as pdf.
Sorry for inconvenience.

**Comment by blueagler** [comment]
Maybe
