### ISSUE TITLE
扩展错误导致的翻译受限

### ISSUE THREAD

**Issue by emilasion** [blueagler/DeepL-Crack#19]
打开deepl网站后提示
![23921672717493_ pic](https://user-images.githubusercontent.com/120484881/210297928-ab7e54ea-5588-42b2-a5bc-40b4790d158c.jpg)
然后翻译文件时提示
你已达到免费使用限制
在chrome扩展里面显示
![331672717732_ pic](https://user-images.githubusercontent.com/120484881/210298112-c3ae27c5-c908-4432-872c-513e053ee6f8.jpg)
用的mac系统 清理过cookie了 也重装过了1.07 但是依旧不可以 大神帮忙解决一下 万分感谢

**Comment by blueagler** [comment]
重写了消息传递
