### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Dramorian** [blueagler/DeepL-Crack#28]
I know this is beyond the project's scope, but can you make a Japanese -> romaji converter? That would be nice. I believe there are plenty of libraries for that ([Kuroshiro](https://github.com/hexenq/kuroshiro) is the best one, I suppose)
I tried Wanakana (it doesn't support kanji) using Tampermonkey, but my nearly non-existent JS knowledge stopped me

**Comment by blueagler** [comment]
Sorry
