### ISSUE TITLE
v1.1.7加载失败，显示无法加载清单

### ISSUE THREAD

**Issue by camui1540** [blueagler/DeepL-Crack#36]
使用chrome和edge分别加载已解压的扩展程序，都弹出提示：
未能成功加载扩展程序文件
C:\Program Files (x86)\Google\Chrome\Plugins\DeepL.Crack.v1.1.7
错误
redirect.json: Internal error while parsing rules.
无法加载清单。

**Comment by blueagler** [comment]
删了重下,换浏览器

**Comment by solidclover** [comment]
我也遇到了这个情况。最后是更换了插件解压文件夹解决的：不要通过系统盘符的位置来导入插件文件夹。我的系统盘盘符的安全策略跟其他盘符不同，具体原因我也不清楚。
