### ISSUE TITLE
v1.1.7问题：您已达到免费使用限制

### ISSUE THREAD

**Issue by mistclouds99** [blueagler/DeepL-Crack#38]
Chrome以及edge都装了这个插件，插件右上角显示了登录了账户，右下角也显示已翻译文件概览、试用期和文档翻译。可是文档翻译了几次之后就提示：“需要继续翻译吗？免费试用DeepL Pro。您已达到免费使用限制。请稍后再试，或[30天免费试用DeepL Pro](https://www.deepl.com/pro?cta=docTrans-rate-limit)，以即时翻译更多文件。”尝试更换浏览器安装插件或是换ip还是相同的问题

**Comment by Vast-Geer** [comment]
我也是这个问题

**Comment by LeKDTrey5** [comment]
不要用文档翻译不就行了

**Comment by blueagler** [comment]
先换ip再点clean cookie

**Comment by innnocencesun** [comment]
请问怎么换IP呢？
