### ISSUE TITLE
How do you translate documents? 

### ISSUE THREAD

**Issue by I-CyberDaun-I** [blueagler/DeepL-Crack#4]
Hello, I registered on this site to inform you of an error. When I try to translate a document, this error appears, it was not present in your video. I waited a long time, cleared cookies, installed clean chrome on the virtual machine, enabled VPN, but nothing helped me. Can you tell me what to do?
p.s. I'm from russia, so everything is in rus
![ошибка](https://user-images.githubusercontent.com/111432204/185107622-5aea8644-b16b-4650-bf6b-17c090fec7fc.png)

**Comment by blueagler** [comment]
pdf issue will be fix in the next version

**Comment by I-CyberDaun-I** [comment]
Great, I can't wait.
