### ISSUE TITLE
Failed to get token: Failed to fetch

### ISSUE THREAD

**Issue by lzxxyn** [blueagler/DeepL-Crack#40]
<img width="229" alt="微信截图_20230331203002" src="https://user-images.githubusercontent.com/90491234/229120586-45842701-480d-4922-b45a-f3b86b521f58.png">

**Comment by blueagler** [comment]
你可以测试能否打开https://serverless.blueagle.top

**Comment by lzxxyn** [comment]
好的，感谢！ 香港也不行是嘛
