### ISSUE TITLE
V1.1.8无法安装扩展程序，报错如下

### ISSUE THREAD

**Issue by camui1540** [blueagler/DeepL-Crack#42]
未能成功加载扩展程序
文件
C:\Program Files (x86)\Google\Chrome\Plugins\DeepL.Crack.v1.1.8
错误
redirect.json: Internal error while parsing rules.
无法加载清单。

**Comment by camui1540** [comment]
已经试了edge、chrome、edge dev等不同浏览器全提示类似错误。更新浏览器到最新版本也不行。
和上面一样或者这种：
“清单文件缺失或不可读取
无法加载清单”

**Comment by blueagler** [comment]
Issue outdated, you can try the latest version
