### ISSUE TITLE
Regarding too many IP request issue and the readme

### ISSUE THREAD

**Issue by VelvetRoom2** [blueagler/DeepL-Crack#43]
Hello. No matter how many times I clean the browser cache and cookies after changing into a new IP, the too many request from your IP issue persists. Plus, I don't understand this line in the readme "- Use DeepL Pro Account Cookies/DeepL Api Free Token to translate." what do you mean by token here?

**Comment by blueagler** [comment]
It means your network is temporarily blocked by DeepL and everyone using the same network cannot access deepL too(because your abuse). You can only switch your network

**Comment by nimbus2332** [comment]
> It means your network is temporarily blocked by DeepL and everyone using the same network cannot access deepL too(because your abuse). You can only switch your network

What address do I need to register in my Proxyifier?

Added www2.deep but still an error about the IP limit
