### ISSUE TITLE
Your document has more characters than your usage limit.

### ISSUE THREAD

**Issue by aki2273** [blueagler/DeepL-Crack#44]
Want to translate longer documents?
Try DeepL Pro for free.
Your document has more characters than your usage limit. [Try DeepL Pro for 30 days free](https://www.deepl.com/pro?cta=docTrans-file-too-many-characters) to translate longer documents with up to 1 million characters and get more premium features.

Can you bypass this please?

**Comment by blueagler** [comment]
This extension does not support unlimited sized file, you can split it or use text translation
