### ISSUE TITLE
Cannot see translated document after upload

### ISSUE THREAD

**Issue by nissansz** [blueagler/DeepL-Crack#54]
![image](https://github.com/blueagler/DeepL-Crack/assets/41010669/5173cb9a-e98f-42ec-9b92-916f9e10eb53)

![image](https://github.com/blueagler/DeepL-Crack/assets/41010669/e570bf56-43f4-4923-adb6-0b7fa1d0f171)

**Comment by anyUesr** [comment]
+1, same question

**Comment by blueagler** [comment]
最新版本已修复
latest version fixed
