### ISSUE TITLE
Where to see result for "Unlock Formal/informal tone"?

### ISSUE THREAD

**Issue by nissansz** [blueagler/DeepL-Crack#55]
Where to see result for "Unlock Formal/informal tone"?

**Comment by blueagler** [comment]
According to DeepL, it is only available to few target languages. You can try different languages

**Comment by nissansz** [comment]
Cannot use this plugin already. I updated to 1.2.2 too.
Cannot see login result. Cannot use.

**Comment by nissansz** [comment]
Can use again now.
