### ISSUE TITLE
关于最近突然无法翻译的问题

### ISSUE THREAD

**Issue by UNSCs117** [blueagler/DeepL-Crack#58]
之前这个扩展用的好好的，但是最近不知道发生了什么，只要启用了这个扩展后就无法翻译了。本人用的edge，扩展是v1.2.1，已经尝试过重装扩展，甚至换个新浏览器后安装扩展，均出现一样的问题(见下图)：
![2](https://github.com/blueagler/DeepL-Crack/assets/39910838/ff76cf5f-d4df-4ea7-b10d-df51370fb829)
右侧翻译结果甚至没有转圈，无论左侧输入什么右侧都是空的。我还注意到右上角的企业用户标识已经消失，star按钮和star数的元素直接叠在一起了。唯一可用的是翻译文件功能(这一部分显示的仍是破解后的样子)

附上edge的扩展详情页：
![3](https://github.com/blueagler/DeepL-Crack/assets/39910838/5849e6a5-2660-4144-afd5-3aafee28172e)

尝试改过token，用机场换过ip，甚至重新安装了个chrome后使用这个扩展仍有同样的问题。只有关闭扩展才能正常使用。

**Comment by ryq0711** [comment]
我也这样，应该是封了

**Comment by blueagler** [comment]
是的,但是最新版本解决了

**Comment by UNSCs117** [comment]
哦速度真的好快，昨天刚发现这个问题今天就修复了，666
