### ISSUE TITLE
Suggestion (potentially valid)

### ISSUE THREAD

**Issue by taozhiyu** [blueagler/DeepL-Crack#6]
Hi, the plugin seems to be working, but as the readme belongs to, oversized data can still cause abnormal requests.

Is it possible to reduce the problems caused by frequent requests by increasing the time interval between successive translation requests?

Too fast a request will result in a 429 error status code, as shown below: 

![image](https://user-images.githubusercontent.com/49258735/196065578-84a647a0-b8e3-4775-9bca-4d9821a5b0e8.png)

All gratitude, thanks for sharing.

**Comment by blueagler** [comment]
if you can give the detailed limit rate
