### ISSUE TITLE
Translated document docx cannot be editted. And there is Deepl logo.

### ISSUE THREAD

**Issue by nissansz** [blueagler/DeepL-Crack#60]
Translated document docx cannot be editted. And there is Deepl logo.

**Comment by blueagler** [comment]
![image](https://github.com/blueagler/DeepL-Crack/assets/61572188/ddb54ae5-9a5a-42e9-a640-f9f44054cc11)

Can't you see that unlock icon?

**Comment by nissansz** [comment]
Thank you. It works after I clicked decrypt logo. Then download.
