### ISSUE TITLE
Not bypass/work properly - only STARTER account - NO ADVANCED / ULTIMATE 

### ISSUE THREAD

**Issue by mdta** [blueagler/DeepL-Crack#7]
This extension not full bypass the limit of DeepL: 
Extension allow max to download 10 MB file and 5000 limit is still enable. 
Basically The extension allow only to obtain a "STARTER" plan account, this extension not enable a ADVANCED or ULTIMATE account.
So is not full working.

**Comment by blueagler** [comment]
read the README
