### ISSUE TITLE
无法访问网站了 DNS points to prohibited IP _ www.deepl.com _ Cloudflare.html

### ISSUE THREAD

**Issue by nissansz** [blueagler/DeepL-Crack#75]
无法访问网站了 DNS points to prohibited IP _ www.deepl.com _ Cloudflare.html

**Comment by Arming621** [comment]
Same issue.

**Comment by Liaowag** [comment]
same issue.

**Comment by zhLeon521** [comment]
same issue.

**Comment by pumperking** [comment]
Error 1000
DNS points to prohibited IP
What happened?
You've requested a page on a website (www.deepl.com) that is on the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. Unfortunately, it is resolving to an IP address that is creating a conflict within Cloudflare's system.

What can I do?
If you are the owner of this website:
you should [login to Cloudflare](https://www.cloudflare.com/login?utm_source=error_100x) and change the DNS A records for www.deepl.com to resolve to a different IP address.


no problem when crack is off.

**Comment by FLOWERpapa** [comment]
same issue but u can reload to fix error

**Comment by blueagler** [comment]
update and click clean cookie
