### ISSUE TITLE
not fixed

### ISSUE THREAD

**Issue by ASKUTKRIMSON** [blueagler/DeepL-Crack#76]
![image](https://github.com/blueagler/DeepL-Crack/assets/84001806/3bd33eca-71af-498a-ae0b-c54150f350d9)

**Comment by ASKUTKRIMSON** [comment]
1.2.6

**Comment by blueagler** [comment]
WHta?
did you click that cookie button

**Comment by ASKUTKRIMSON** [comment]
Yes

**Comment by ASKUTKRIMSON** [comment]
Mean, the lettering's floating
