### ISSUE TITLE
v1.0.3 Error

### ISSUE THREAD

**Issue by SA-GIMA** [blueagler/DeepL-Crack#9]
Hello author, after seeing the pop-up window of version 1.0.2 prompting timeout, I installed your plug-in version 1.0.3, but the file still cannot be translated on the deepl website, and an error will pop up: something went wrong. Please try again later.
作者您好，看到1.0.2版本弹窗提示超时后，我安装了您的1.0.3版本插件，deepl网站上依旧不能翻译文件，会弹出错误：出错了。请稍后再试。

![image](https://user-images.githubusercontent.com/58975377/203680438-bdb48699-dfb0-41d8-b13e-a2d9bf9fa0aa.png)

**Comment by SA-GIMA** [comment]
How should I solve this problem

**Comment by blueagler** [comment]
will fix

**Comment by blueagler** [comment]
fixed
